backup:
  method: "RCLONE"
  prefix: "dropbox:IOTstack/backups"
  retain: 45

restore:
  method: "RCLONE"
  prefix: "dropbox:IOTstack/backups"

# --- settings above this line are active. Those below are examples ---

backup-rsync:
  method: "RSYNC"
  prefix: "user@host:path/to/prefix/folder"
  retain: 8

restore-rsync:
  method: "RSYNC"
  prefix: "user@host:path/to/prefix/folder"

# ---------------------------------------------------------------------

backup-rclone:
  method: "RCLONE"
  prefix: "dropbox:path/to/prefix/folder"
  retain: 8

restore-rclone:
  method: "RCLONE"
  prefix: "dropbox:path/to/prefix/folder"

# ---------------------------------------------------------------------

backup-scp:
  method: "SCP"
  prefix: "user@host:path/to/prefix/folder"
  retain: 8

restore-scp:
  method: "SCP"
  prefix: "user@host:path/to/prefix/folder"
